### ISSUE TITLE
Cannot find buildhelper(m2e connector for build-helper-maven-plugin)

### ISSUE THREAD

**Issue by xg578962913** [eclipse-m2e/m2e-discovery-catalog#3]
I'm not sure if I should ask here,But I can't find anywhere else.
Before that, I install buildhelper in Eclipse by following these steps
Eclipse - Preferences - Maven - Discovery
![TFU1_8}BYU8@0610%%4_J7E](https://user-images.githubusercontent.com/24224600/209130255-025da5ed-26b6-467b-a6d8-a5d757e539c9.png)
![image](https://user-images.githubusercontent.com/24224600/209130351-f120489a-0d7b-493f-b898-63575f6fc69a.png)
When I use the new version of Eclipse, I find that the catalog URL has changed

old :https://download.eclipse.org/technology/m2e/discovery/directory-1.15.xml
new :https://github.com/eclipse-m2e/m2e-discovery-catalog/releases/download/2.x/catalog-2.x.xml (That's why I'm asking here)
I found that buildhelper disappeared
![image](https://user-images.githubusercontent.com/24224600/209131123-fd40fd5f-bbf3-4e0b-be0c-12be2fad26d5.png)
I want to know where the buildhelper (m2e connector for build-helper-maven-plugin)has gone. Is there any substitute? Or how can I download him again

**Comment by mickaelistria** [comment]
I think best is that you ask the question at https://github.com/tesla/m2eclipse-buildhelper (which provides the connector). But my first impression is that the connector is not maintained any more.
But m2e has improved regarding executing Mojos in the IDE, so maybe you can just get rid of the connector and use the default behavior (or configure m2e to execute the mojo) and you'd get better results.

**Comment by brychcy** [comment]
This is a show-stopper for us that stops us from using the new m2e at all - I'm currently installing the old m2e version into the current eclipse.

It looks like  https://github.com/tesla/m2eclipse-buildhelper doesn't have any java code at all.

I guess what it really does, is to provide https://github.com/tesla/m2eclipse-buildhelper/blob/master/org.sonatype.m2e.buildhelper/lifecycle-mapping-metadata.xml

So the only thing that stops it from working is the version change, right?

**Comment by mickaelistria** [comment]
> So the only thing that stops it from working is the version change, right?

Probably yes. Please try it and it it works and if it seems doable from IP POV, this particular adapter might be worth being included by default in m2e.

**Comment by fbricon** [comment]
I restored the buildhelper connector in the catalog. Note that it's actually unnecessary if you use build-helper-maven-plugin >= 3.0.0

**Comment by brychcy** [comment]
Thanks Fred, it works now!
Also thanks for the hint to newer build-helper-maven-plugin.
